# conda environment name
conda_env: "cfmc_env"

# input pdbs for packmol
alchemical_ligand_pdb: "pdbs/lig_water.pdb"
solvent_pdb: "pdbs/reg_eth.pdb"
solute_pdb: "pdbs/reg_water.pdb"

# molecule naming
alchemical_ligand_name: "LIG"
solute_name: "SOL"
solvent_name: "ETH"

# mdps for GROMACS
em_mdp: "mdps/em.mdp"
nvt_mdp: "mdps/nvt.mdp"
npt_mdp: "mdps/npt.mdp"
prod_mdp: "mdps/prod.mdp"

# itps for GROMACS
all_atomtypes_itp: "itps/all_atomtypes.itp"
alchemical_ligand_itp: "itps/lig_water.itp"
solute_itp: "itps/tip3p.itp"
solvent_itp: "itps/ethanol_alone.itp"

# runtime args
n_replicates: 1
n_solute: 150 # this is the total number of solute particles (i.e. inclusive of the transforming molecule)
n_solvent: 75
nt: 12
box_size: 60
